- name: Terraform Apply
  hosts: terraform
  gather_facts: false

  tasks:
    - name: Terraform apply
      ansible.builtin.command:
        cmd: terraform apply -auto-approve /tmp/{{ vm_name }}.tfplan
        chdir: /opt/terraform/azure-vm
      environment:
        ARM_SUBSCRIPTION_ID: "{{ lookup('ansible.builtin.env', 'AZURE_SUBSCRIPTION_ID') }}"
        ARM_CLIENT_ID: "{{ lookup('ansible.builtin.env', 'AZURE_CLIENT_ID') }}"
        ARM_CLIENT_SECRET: "{{ lookup('ansible.builtin.env', 'AZURE_SECRET') }}"
        ARM_TENANT_ID: "{{ lookup('ansible.builtin.env', 'AZURE_TENANT') }}"