---
- name: List Azure virtual machines
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import Azure infrastructure role
      ansible.builtin.import_role:
        name: azure
