---
- name: Preflight vCenter privilege check before clone
  hosts: localhost
  gather_facts: false
  vars:
    vm_cluster_id: "domain-c1198154"
    vm_datastore_id: "datastore-1198166"
    vm_resource_pool_id: "resgroup-1201139"
    vm_folder_id: "group-v1159426"
    # Example: vm_folder_id: "{{ lookup('vmware.vmware_rest.folder_moid', '/my_dc/vm') }}"
    #vm_source_id: "vm-1209383"
    vm_network_id: "dvportgroup-1201111"
  tasks:
  - name: Create a VM
    vmware.vmware_rest.vcenter_vm:
      placement:
        cluster: "{{ vm_cluster_id }}"
        datastore: "{{ vm_datastore_id }}"
        folder: "{{ vm_folder_id }}"
        resource_pool: "{{ vm_resource_pool_id }}"
      name: test_vm1
      guest_OS: RHEL_8_64
      hardware_version: VMX_11
      cpu:
        hot_add_enabled: true
        count: 2
        cores_per_socket: 1
      memory:
        hot_add_enabled: true
        size_MiB: 1024
      disks:
      - type: SATA
        sata:
          bus: 0
          unit: 0
        new_vmdk:
          name: system_disk
          capacity: 21474836480
      cdroms:
      - type: SATA
        sata:
          bus: 0
          unit: 2
      nics:
      - type: VMXNET3
        start_connected: true
        allow_guest_control: false
        backing:
          type: 'DISTRIBUTED_PORTGROUP'
          network: "{{ vm_network_id }}"
    register: my_vm