---
- name: Provision Azure VM
  hosts: terraform
  gather_facts: false
  vars:
    terraform_dir: /opt/terraform/azure-vm/azure-terra

  tasks:

    - name: Terraform init
      ansible.builtin.command:
        cmd: terraform init
        chdir: "{{ terraform_dir }}"
      environment: "{{ terraform_environment }}"

    - name: Terraform plan
      ansible.builtin.command:
        cmd: >
          terraform plan
          -var="resource_group_name={{ resource_group_name }}"
          -var="location={{ location }}"
          -var="vm_name={{ vm_name }}"
          -var="vm_size={{ vm_size }}"
          -var="vnet_name={{ vnet_name }}"
          -var="subnet_name={{ subnet_name }}"
          -var="admin_password={{ admin_password }}"
        chdir: "{{ terraform_dir }}"
        environment:
          ARM_SUBSCRIPTION_ID: "{{ AZURE_SUBSCRIPTION_ID }}"
          ARM_CLIENT_ID: "{{ AZURE_CLIENT_ID }}"
          ARM_CLIENT_SECRET: "{{ AZURE_SECRET }}"
          ARM_TENANT_ID: "{{ AZURE_TENANT }}"

      register: terraform_plan

    - name: Show Terraform plan
      ansible.builtin.debug:
        var: terraform_plan.stdout