- name: Rolling update HTTP servers
  hosts: webservers
  # serial: 1
  # serial:
  #   - 1
  #   - 5
  #   - "20%"
  # max_fail_percentage: 30%
  tasks:

    - name: Remove server from HAProxy
      community.general.haproxy:
        state: disabled
        host: "{{ inventory_hostname }}"
      delegate_to: haproxy
      # delegate_facts: true

    - name: Update httpd
      ansible.builtin.dnf:
        name: httpd
        state: latest
    - name: Sleep for 10 seconds to allow HAProxy to update
      ansible.builtin.pause:
        seconds: 10
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Add server back to HAProxy
      community.general.haproxy:
        state: enabled
        host: "{{ ansible_facts['fqdn'] }}"
      delegate_to: haproxy