---
- name: Prepare all Kubernetes nodes
  hosts: control_plane:worker
  become: true
  gather_facts: false
  roles:
    - common
    - crio
    - kubeadm

- name: Initialize control plane
  hosts: control_plane
  become: true
  serial: 1
  roles:
    - kubeadm_control_plane
    - role: cni
      when: inventory_hostname == groups['control_plane'][0]

- name: Join worker nodes
  hosts: worker
  become: true
  roles:
    - kubeadm_worker