---
- name: Observe Ansible module transfer
  hosts: workers
  gather_facts: false

  tasks:
  - name: Lay thong tin Appliance tu vCenter (vmware.vmware)
    vmware.vmware.appliance_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ validate_certs }}"
    register: vcenter_appliance_info

  - name: Hien thi ket qua
    ansible.builtin.debug:
      var: vcenter_appliance_info
