---
- name: Test tao VM su dung community.vmware.vmware_guest
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get distributed switches
      community.vmware.vmware_dvswitch_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter }}"
      register: dvs_info

    - debug:
      var: dvs_info.distributed_virtual_switches
    - name: Create a virtual machine
      community.vmware.vmware_guest:
        folder: "/Amigo/vm/Software-2"
        datacenter: "Amigo"
        cluster: "Amigo 2"
        resource_pool: "Software-2"
        name: testvm_som
        state: poweredon
        guest_id: rhel8_64Guest
        disk:
        - size_gb: 20
          type: thin
          datastore: vsanDatastore
        # Add another disk from an existing VMDK
        hardware:
          memory_mb: 2048
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          memory_reservation_lock: true
          mem_limit: 8096
          mem_reservation: 4096
          cpu_shares_level: "high"
          mem_shares_level: "high"
          cpu_limit: 8096
          cpu_reservation: 4096
          max_connections: 5
          hotadd_cpu: true
          hotremove_cpu: true
          hotadd_memory: false
          version: 12 # Hardware version of virtual machine
          boot_firmware: "efi"
        cdrom:
            - controller_number: 0
              unit_number: 0
              state: present
              type: iso
              iso_path: "[vsanDatastore] b4b80e6a-0a46-ae2f-9e7e-6c92cf75ed90/rhel-9.3-x86_64-dvd.iso"
        networks:
        - name: '192.168.50.0'
        #wait_for_ip_address: true
      delegate_to: localhost
      register: deploy