- name: Create a VM
  hosts: localhost
  gather_facts: false
  vars:
      vm_cluster_id: "domain-c1001"
      vm_datastore_id: "datastore-1002"
      vm_resource_pool_id: "resgroup-1004"
  tasks:
  - name: Create a clone of a VM
    vmware.vmware_rest.vcenter_vm:
      placement:
        cluster: "{{ vm_cluster_id }}"
        datastore: "{{ vm_datastore_id }}"
        resource_pool: "{{ vm_resource_pool_id }}"
      source: 'vm-1209383'
      name: test_vm3
      state: clone
    register: my_clone_vm
