---
- name: Khoi tao cau hinh may ao co ban
  vmware.vmware.vm:
    validate_certs: false

    datacenter: "{{ datacenter_name | default('Datacenter') }}"
    cluster: "{{ cluster_name | default('cluster1') }}"
    resource_pool: "{{ resource_pool | default('Resources') }}"
    datastore: "{{ datastore_name | default('datastore1') }}"
    folder: "{{ folder_name | default('/Amigo/vm/Software-2') }}"
    name: "{{ vm_name | default('test-vmware-module-01') }}"
    guest_id: "{{ guest_id | default('rhel8_64Guest') }}"

    cpu:
      cores: "{{ cpu_cores | default(2) }}"
      cores_per_socket: "{{ cpu_cores_per_socket | default(1) }}"
    memory:
      size_mb: "{{ memory_size_mb | default(2048) }}"

    scsi_controllers:
      - controller_type: paravirtual
        bus_number: 0
    network_adapters:
      - adapter_type: "{{ adapter_type | default('vmxnet3') }}"
        network: "{{ network_name | default('192.168.50.0') }}"
        connect_at_power_on: true
    disks:
      - size: "{{ disk_size | default('20gb') }}"
        provisioning: thin
        device_node: "SCSI(0:0)"

  register: _new_vm

- name: Bat nguon may ao sau khi tao
  vmware.vmware.vm_powerstate:
    validate_certs: false
    datacenter: "{{ datacenter_name | default('Datacenter') }}"
    moid: "{{ _new_vm.vm.moid }}"
    state: powered-on
